### ISSUE TITLE
Documentation or tips to implement

### ISSUE THREAD

**Issue by joaocolaco** [onekiloparsec/KPCJumpBarControl#1]
Hi,

I'm toying with this control but it doesn't work as documented since version 0.7.0. The same happens in the sample code.

Reviewing the code it seems to need to be bound to a NSTreeController. Do you have any advice or tips on how to do it?

Thanks

**Comment by onekiloparsec** [comment]
Hi. I haven't touch this control since quite a while, and indeed, it may be a bit difficult to grasp. It is not finished in fact, because the app it was supposed to work in has been transformed into a web service... But I'll try to check this again.

**Comment by joaocolaco** [comment]
Thanks!
